// Invoice
export const INVOICE_UPDATE = 'INVOICE_UPDATE';

// UI
export const UI_CHANGE_LANGUAGE = 'UI_CHANGE_LANGUAGE';

// Settings
export const SETTINGS_RELOAD_CONFIGS  = 'SETTINGS_RELOAD_CONFIGS';
export const SETTINGS_UPDATE_CONFIGS = 'SETTINGS_UPDATE_CONFIGS';

// Profile
export const SETTINGS_UPDATE_PROFILE = 'SETTINGS_UPDATE_PROFILE';

