// Invoice
export const INVOICE_UPDATE = 'INVOICE_UPDATE';

// Settings
export const SETTINGS_RELOAD_CONFIGS  = 'SETTINGS_RELOAD_CONFIGS';
export const SETTINGS_UPDATE_CONFIGS = 'SETTINGS_UPDATE_CONFIGS';
