// Invoice
export const INVOICE_UPDATE = 'INVOICE_UPDATE';

// Settings
export const SETTINGS_UPDATE_CONFIGS = 'SETTINGS_UPDATE_CONFIGS';
export const SETTINGS_UPDATE_TEMPLATE = 'SETTINGS_UPDATE_TEMPLATE';


